nameOverride: tic-tac-toe
fullnameOverride: tic-tac-toe-app

replicaCount: 2

image:
  repository: ghcr.io/gesatessa/devsecops-tic-tac-toe-react
  tag: "sha-ad8c62fc667bc3c5133603ffd442f9d17bb2b5dc"
  pullPolicy: IfNotPresent

imagePullSecret: github-container-registry

service:
  type: ClusterIP
  nodePort: 32123

resources:
  limits:
    cpu: "0.5"
    memory: "512Mi"
  requests:
    cpu: "0.2"
    memory: "256Mi"

ingress:
  enabled: true
