apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tic-tac-toe
  region: us-east-1

managedNodeGroups:
  - name: ttt-game-nodes
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    spot: true
